### PR TITLE
Rename gamethrive to onesignal

### PR DESCRIPTION
**Pull request by jishnu7**
This change is [Reviewable](https://reviewable.io/reviews/hashcube/gamethrive/2)

### CODE REVIEW

**Comment by rampr** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[android/LICENSE, line 1 [r1]](https://reviewable.io:443/reviews/hashcube/gamethrive/2#-KPkzlsagWBidBVCTlMS:-KPkzlsagWBidBVCTlMT:b-imts0q) ([raw file](https://github.com/hashcube/gamethrive/blob/9d863723b06ab89540dc8a82f06bc639869316df/android/LICENSE#L1)):_

> ```
> Modified MIT License
> ```

Not needed ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hashcube/gamethrive/2)_

**Comment by jishnu7** [comment]
@rampr That file is not needed. So I removed it.

**Comment by rampr** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hashcube/gamethrive/2#-:-KPl64it7KYMuuIV2cNY:bnfp4nl)_

**Comment by rampr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[android/LICENSE, line 1 [r1]](https://reviewable.io:443/reviews/hashcube/gamethrive/2#-KPkzlsagWBidBVCTlMS:-KPl67iIAr9eU5YV9ZiB:bb6ywmx) ([raw file](https://github.com/hashcube/gamethrive/blob/9d863723b06ab89540dc8a82f06bc639869316df/android/LICENSE#L1)):_
<details><summary>

<i>Previously, rampr (ram) wrote…</i></summary>



> Not needed ?
> </details>
> LGTM

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hashcube/gamethrive/2)_

**Comment by rohanhc** [comment]
LGTM

**Pull request merged**
